### PR TITLE
Replace deprecated dependencies and fix tests.

### PR DESCRIPTION
**Pull request by divark**

### CODE REVIEW

**Comment by divark** [comment]
I noticed that in the `.travis.yml` file that the rust version is still set to 1.40.0 for stable. However, [gtk3-rs](https://github.com/gtk-rs/gtk3-rs) recommends having 1.56.0 minimum. What do you think about me changing the version in the travis configuration to 1.56.0?

**Comment by GuillaumeGomez** [comment]
travis doesn't work anymore and we never setup github actions...

**Comment by divark** [comment]
@GuillaumeGomez I have a working CI with GitHub Actions from my repository for both [Linux/MacOS](https://github.com/divark/narrative-director-rs/blob/main/.github/workflows/ci.yml) and [Windows](https://github.com/divark/narrative-director-rs/blob/main/.github/workflows/windows-ci.yml). I would be willing to get that included here with some modifications if you'd like. What do you think?

**Comment by GuillaumeGomez** [comment]
Can you open another PR to add the github actions CI please? Then we will use it on this PR. :)

**Comment by divark** [comment]
Sure thing! I've created a draft PR in #49.

**Comment by GuillaumeGomez** [comment]
Please rebase this one now so we can see how the CI will complain. 😝

**Comment by divark** [comment]
[Both CIs](https://github.com/divark/gtk-test/actions) pass with these new changes. Hooray! What next?

**Comment by GuillaumeGomez** [comment]
I'll merge as is because I also want to use this opportunity to upgrade to edition 2021. Thanks!

**Pull request merged**
